### ISSUE TITLE
wont work in Dragonflight pre patch

### ISSUE THREAD

**Issue by bubfeeld** [Pingumania/PhanxFont#1]
this is the error i get 

5x Interface/AddOns/PhanxFont/Addon.lua:41: Usage: self:SetFont(fontFile, height, flags)
[string "=[C]"]: in function `SetFont'
[string "@Interface/AddOns/PhanxFont/Addon.lua"]:41: in function `SetFont'
[string "@Interface/AddOns/PhanxFont/Addon.lua"]:69: in function `SetFonts'
[string "@Interface/AddOns/PhanxFont/Addon.lua"]:190: in function <Interface/AddOns/PhanxFont/Addon.lua:186>

Locals:
(*temporary) = AchievementFont_Small {
 0 = <userdata>
}
(*temporary) = "Fonts\FRIZQT__.TTF"
(*temporary) = 17
(*temporary) = nil

Im using the latest download from feb

**Comment by Pingumania** [comment]
Should be fixed in the latest version.

**Comment by bubfeeld** [comment]
WOW!! thanks a million!!!! You are a LIFESAVER!!!
